# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/kaif22mohammed/aa8a9af32d144c535b00e87682958590/untitled3.ipynb
"""

import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/balaji2v/Inceptez_Batch19/main/Demand_txn_updated.csv"
df = pd.read_csv(url)
df

#1
df.head(15)

df.dtypes

#2
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])
df

#3
a8_1 = df[df["Transaction_Date"] > '2016-08-01']
a8_1

#4
df["Mapped_Sales_Type"].unique()

#5
df[df["Avg_Discount_Percent_On_Discounted_Items"] < 1.0]

#5
df[(df['Avg_Discount_Percent_On_Discounted_Items'] >= 1.0)]

#6
G = df.groupby(['City', 'Mapped_Sales_Type', 'Mapped_Item_Code', 'Transaction_Date'])['Quantity_Sold'].sum()
G

#6
G = df.groupby(['City', 'Mapped_Sales_Type', 'Mapped_Item_Code', 'Transaction_Date'])['Median_Price'].median()
G

#6
G = df.groupby(['City', 'Mapped_Sales_Type', 'Mapped_Item_Code', 'Transaction_Date'])['Effective_Price'].median()
G

#7
last5 = df['Effective_Price'].notnull()
df[last5].tail(5)

#8
df.loc[(df['City']=='Chennai') & (df['Mapped_Sales_Type']=='Delivery')].head(5)

#9
df[df["Day"].isin(["Mon", "Tues", "Wed"])]

#10
df.loc[df['Percent_Quantity_With_Discount']!= 0.0]

#11
import numpy as np
df['Range']=np.where(df['Effective_Price'] > 500 , 1 ,0.5)
df.head(10)

#12
df1 = pd.read_csv("https://raw.githubusercontent.com/balaji2v/Inceptez_Batch19/main/Demand_txn_updated.csv")
df1["Percent_Quantity_With_Discount"].fillna(df1["Percent_Quantity_With_Discount"].mean(),inplace = True)
df1.head()